name: cloudy
description: "Cloudy is a sleek weather app with a Live Home Screen Widget that shows real-time weather updates directly on the home screen"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/default.jpg
    - lib/core/assets/clear.jpg
    - lib/core/assets/cloudy.jpg
    - lib/core/assets/partially-cloudy.jpg
    - lib/core/assets/rainy.jpg
    - lib/core/assets/storm.jpg
    - lib/core/assets/sunny.jpg
    - lib/core/assets/thunder.jpg